-- 0003_page_clipboard_ops.sql
-- Page duplicate / cut-copy-paste support for the editor clipboard system.
-- These RPCs mirror the atomic, invariant-preserving pattern established by the
-- 0002 page-management RPCs (defer the unique(booklet_id, page_order) check so
-- a multi-row renumber can't transiently collide; re-enforce "only the last
-- page may be is_quiz_page" after any structural change) and reuse the exact
-- element-insert shape from save_page_elements (0001) so element copying stays
-- consistent: incoming element `id`/`page_id` are ignored and fresh ids are
-- generated by the table default — guaranteeing no duplicate ids.

-- Inserts a brand-new page directly after p_after_page_id (or at the end when
-- it is null) and fills it with p_elements. This is the shared primitive behind
-- both "Paste Page" (elements come from the in-memory page clipboard) and
-- "Duplicate Page" (duplicate_page below reads the source page's elements and
-- calls this). Returns the new page row.
create function insert_page_with_elements(
  p_booklet_id uuid,
  p_after_page_id uuid,
  p_is_quiz_page boolean,
  p_elements jsonb
)
returns pages as $$
declare
  v_after_order int;
  v_new_order int;
  new_page pages;
begin
  if not is_admin() then
    raise exception 'not authorized';
  end if;

  set constraints pages_booklet_id_page_order_key deferred;

  if p_after_page_id is null then
    -- Append at the end of the booklet.
    v_new_order := (select coalesce(max(page_order) + 1, 0) from pages where booklet_id = p_booklet_id);
  else
    select page_order into v_after_order
    from pages
    where id = p_after_page_id and booklet_id = p_booklet_id;
    if v_after_order is null then
      raise exception 'after-page not found in this booklet';
    end if;
    v_new_order := v_after_order + 1;
    -- Open a gap at the insertion slot by pushing every later page down one.
    update pages set page_order = page_order + 1
    where booklet_id = p_booklet_id and page_order >= v_new_order;
  end if;

  insert into pages (booklet_id, page_order, is_quiz_page)
  values (p_booklet_id, v_new_order, coalesce(p_is_quiz_page, false))
  returning * into new_page;

  insert into page_elements (
    page_id, type, z_index, x, y, w, h, rotation, props
  )
  select
    new_page.id,
    (elem->>'type')::text,
    coalesce((elem->>'z_index')::int, 0),
    (elem->>'x')::numeric,
    (elem->>'y')::numeric,
    (elem->>'w')::numeric,
    (elem->>'h')::numeric,
    coalesce((elem->>'rotation')::numeric, 0),
    coalesce(elem->'props', '{}'::jsonb)
  from jsonb_array_elements(coalesce(p_elements, '[]'::jsonb)) as elem;

  -- A mid-book insertion can never legitimately be the quiz page; re-enforce
  -- the invariant (demote any non-last page that is still flagged).
  update pages set is_quiz_page = false
  where booklet_id = p_booklet_id
    and is_quiz_page = true
    and page_order <> (select max(page_order) from pages where booklet_id = p_booklet_id);

  return new_page;
end;
$$ language plpgsql security definer;

-- Duplicates an existing page (its settings + every element) and inserts the
-- copy immediately after the original. Reads the source elements server-side
-- (no client round-trip) and delegates the actual insert/renumber/invariant
-- work to insert_page_with_elements. Returns the new page row.
create function duplicate_page(p_page_id uuid)
returns pages as $$
declare
  v_booklet_id uuid;
  v_is_quiz boolean;
  v_elements jsonb;
  new_page pages;
begin
  if not is_admin() then
    raise exception 'not authorized';
  end if;

  select booklet_id, is_quiz_page into v_booklet_id, v_is_quiz
  from pages where id = p_page_id;
  if v_booklet_id is null then
    raise exception 'page not found';
  end if;

  -- Snapshot the source elements as a jsonb array in z-order. id/page_id are
  -- carried along but ignored by insert_page_with_elements (fresh ids minted).
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'type', e.type,
        'z_index', e.z_index,
        'x', e.x,
        'y', e.y,
        'w', e.w,
        'h', e.h,
        'rotation', e.rotation,
        'props', e.props
      )
      order by e.z_index
    ),
    '[]'::jsonb
  )
  into v_elements
  from page_elements e
  where e.page_id = p_page_id;

  new_page := insert_page_with_elements(v_booklet_id, p_page_id, v_is_quiz, v_elements);
  return new_page;
end;
$$ language plpgsql security definer;
